version: '3'

tasks:
  build:
    dir: cmd/nship
    cmds:
      - go build -o ../../bin/nship.exe

  lint:
    cmd: golangci-lint run ./...

  test:
    cmd: go test -v -cover ./...

  site:
    cmd: docker run --rm -p 8000:8000 -v ${PWD}/site:/docs -v ${PWD}/README.md:/docs/docs/index.md squidfunk/mkdocs-material