version: '3'

tasks:
  build:
    dir: cmd/nship
    cmds:
      - go build -o ../../bin/nship.exe

  lint:
    cmd: golangci-lint run ./...

  lint-fix:
    cmd: golangci-lint run ./...

  test:
    cmd: go test -cover ./...