version: '3'

tasks:
  build:
    dir: cmd/nship
    cmds:
      - go build -o ../../bin/nship.exe
      - npx shx cp ../../bin/nship.exe D:/develop/tools/go/path/bin

  lint:
    cmd: golangci-lint run ./...
  lint-fix:
    cmd: golangci-lint run ./...
