site_name: NShip
site_url: https://nship.dev
repo_url: https://github.com/nickalie/nship
theme:
  name: material
  logo: logo256.png
  favicon: favicon.png
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  features:
    - navigation.instant
    - toc.follow
    - toc.integrate
    - content.code.annotate
    - navigation.sections

plugins:
  - search
  - minify:
      minify_html: true

nav:
  - NShip: index.md